{{- if not (and (eq .Values.global.cloud_storage_provider "azure") .Values.global.azure_client_id) }}
PRIVATE_CLOUD_STORAGE_SECRET: "{{ .Values.global.cloud_storage_secret_key }}"
PUBLIC_CLOUD_STORAGE_SECRET: "{{ .Values.global.cloud_storage_secret_key }}"
{{- end }}
