apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-catalogue-migration
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  ai_pipeline_catalogue.sql: |
{{ .Files.Get "files/ai_pipeline_catalogue.sql" | indent 4 }}
