apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "database-import.fullname" . }}-migration-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database-import.labels" . | nindent 4 }}
