apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.name" . }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: litellm
          image: "{{ (index .Values.global .Values.globalImageKey).registry }}/{{ (index .Values.global .Values.globalImageKey).repository }}:{{ (index .Values.global .Values.globalImageKey).tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['--config', '/app/config.yaml', '--host', '0.0.0.0', '--port', {{ .Values.service.port | quote }}]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: LITELLM_LOCAL_MODEL_COST_MAP
              value: "true"
            - name: LITELLM_TELEMETRY
              value: "false"
            - name: DO_NOT_TRACK
              value: "1"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /health/liveliness, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health/liveliness, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.fullname" . }}
