{{- $sa := (.Values.global | default dict).serviceAccount | default dict -}}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if $sa.annotations }}
{{- toYaml $sa.annotations | nindent 4 }}
{{- end }}
{{- end }}