{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "content-service-sa" }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.content_service_client_id }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.content_service_client_id }}
  labels:
    azure.workload.identity/use: "true"
  {{- end }}
{{- end }}
