{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.azure_client_id | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
