{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and .Values.cloud_storage (eq .Values.cloud_storage.type "azure") }}
  name: {{ .Values.global.content_service_sa_name }}
  {{- else }}
  name: {{ include "common.names.fullname" . }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.content_service_client_id }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.content_service_client_id }}
  labels:
    azure.workload.identity/use: "true"
  {{- end }}
{{- end }}
