global:
  env: dev
  environment: dev
  building_block: sunbird-spark
  cloud_storage_access_key:   
  cloud_storage_secret_key: 
  public_container_name: sunbird-spark-dev-public-8eedcadf58
  private_container_name: sunbird-spark-dev-private-8eedcadf58
  dial_state_container_public: sunbird-spark-dev-dial-8eedcadf58
  velero_container_name: sunbird-spark-dev-velero-private-8eedcadf58
  private_ingressgateway_ip: 
  encryption__string: dummy-encryption-string
  random_string: dummy-string
  aws_account_id: 643830915803
  object_storage_endpoint: s3.amazonaws.com
  storage_class: gp2
  cloud_storage_provider: aws
  cloud_storage_region: us-east-1
  service_account_role_arn: 
  
  serviceAccount: 
    create: true
    name: sunbird-sa
    annotations:
      eks.amazonaws.com/role-arn: 

velero:                                                       
  enabled: true
  serviceAccount:
    server:
      create: true
      name: velero-sa
      annotations:
        eks.amazonaws.com/role-arn: 
  credentials:
    useSecret: false
  configuration:
    backupStorageLocation:
      - name: default
        provider: aws
        bucket: "sunbird-spark-dev-velero-private-8eedcadf58"
        config:
          region: us-east-1
    dbbackupbackupStorageLocation:
      - name: dbbackup
        provider: aws
        bucket: "sunbird-spark-dev-velero-private-8eedcadf58"
        config:
          region: us-east-1
    backupSyncPeriod: 15m
    volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: us-east-1
  initContainers:
    - image: velero/velero-plugin-for-aws:v1.8.0
      name: velero-plugin-for-aws
      volumeMounts:
        - mountPath: /target
          name: plugins  

spark: 
  serviceAccount:
    create: false 
    name: "sunbird-sa"            

nginx-public-ingress:
  commonAnnotations:
    reloader.stakater.com/auto: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
