sunbird_content_repo_api_key: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_language_service_api_key: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_learner_service_api_key: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_dial_repo_api_key: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_search_service_api_key: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_plugin_repo_api_key: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_data_service_api_key: "{{ .Values.global.sunbird_admin_api_token }}"
