apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-core-api" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: core-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "common.names.name" . }}
    app.kubernetes.io/component: core-api
  ports:
    - name: http
      port: {{ .Values.coreApi.service.port }}
      targetPort: http
