sunbird_sso_client_secret: "{{ .Values.sunbird_sso_client_secret }}{{ .Values.global.random_string }}"
sunbird_encryption_key: "{{ default .Values.global.random_string .Values.global.sunbird_encryption_key }}"
ekstep_authorization: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_authorization: "{{ .Values.global.sunbird_admin_api_token }}"
google_captcha_private_key: "{{ .Values.global.google_captcha_private_key }}"
sunbird_url_shortner_access_token: "{{ .Values.sunbird_url_shortner_access_token }}"
google_captcha_mobile_private_key: "{{ .Values.google_captcha_mobile_private_key }}"
