{{- if and .Values.enabled (eq (.Values.global.cloud_storage_auth_type | default "workload_identity") "access_key") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yugabyte-backup.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yugabyte-backup.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.global.cloud_service_provider "azure" }}
  storage_key: {{ .Values.global.cloud_storage_secret_key | default "" | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.global.cloud_service_provider "gcp" }}
  gcp-sa.json: {{ .Values.global.cloud_storage_secret_key | default "" | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.global.cloud_service_provider "aws" }}
  aws_access_key_id: {{ .Values.global.cloud_storage_access_key | default "" | b64enc | quote }}
  aws_secret_access_key: {{ .Values.global.cloud_storage_secret_key | default "" | b64enc | quote }}
  {{- end }}
{{- end }}
