name: Docker Build and Push

on:
  push:
    tags:
      - 'spark-v*'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - keycloak-21.1.2
          - keycloak-postgres-query
          - kong-api-scripts
          - sunbird-yugabyte-migrations
          - janusgraph
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker image name and tag
        run: |
          OWNER_LOWERCASE=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          TAG_NAME=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH="${GITHUB_SHA::7}"
          BUILD_TAG="${TAG_NAME}_${COMMIT_HASH}_${GITHUB_RUN_NUMBER}"

          echo "IMAGE_NAME=ghcr.io/${OWNER_LOWERCASE}/${{ matrix.directory }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${BUILD_TAG}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./scripts/${{ matrix.directory }}/Dockerfile ./scripts/${{ matrix.directory }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Tag and push latest
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
