{
 "title": "API Manager",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "api",
    "query": "label_values(kong_http_requests_total,service)"
   },
   {
    "name": "username",
    "query": "label_values(kong_http_requests_total,consumer)"
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"${api}\"}[5m])) by (service)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code=~\"2..|3..\"}[5m])) by (service, code) / ignoring(code) group_left sum(increase(kong_http_requests_total{service=~\"${api}\"}[5m])) by (service)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_http_requests_total{service=~\"$api\"}[$__range])) by (service)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Error %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "4xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code!~\"2..|3..|5..\"}[5m])) by (service, code) / ignoring(code) group_left  sum(increase(kong_http_requests_total{service=~\"${api}\"}[5m])) by (service)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code!~\"2..|3..|4..\"}[5m])) by (service, code) / ignoring(code) group_left  sum(increase(kong_http_requests_total{service=~\"${api}\"}[5m])) by (service)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  { "title": "Latency - Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Total Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_latency_ms_sum{service=~\"${api}\"}[5m]) / rate(kong_request_latency_ms_count{service=~\"${api}\"}[5m])) by (service)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Average Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_upstream_latency_ms_sum{service=~\"${api}\"}[5m])) by (service)  / sum(rate(kong_upstream_latency_ms_count{service=~\"${api}\"}[5m])) by (service)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Success / Error Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Success Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code=~\"2..|3..\"}[5m])) by (service, code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "4xx Error Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code!~\"2..|3..|5..\"}[5m])) by (service, code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx Error Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code!~\"2..|3..|4..\"}[5m])) by (service, code)",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Latency Percentile - 99",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Latency - 99 Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service=~\"${api}\"}[5m])) by (service,le))",
       "legendFormat": "p99-{{api}}"
      }
     ]
    },
    {
     "title": "Upstream Latency - 99 Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service=~\"${api}\"}[5m])) by (service,le))",
       "legendFormat": "p99-{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Percentile - 95",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Latency - 95 Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service=~\"${api}\"}[5m])) by (service,le))",
       "legendFormat": "p95-{{api}}"
      }
     ]
    },
    {
     "title": "Upstream Latency - 95 Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service=~\"${api}\"}[5m])) by (service,le))",
       "legendFormat": "p95-{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Percentile - 50",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Latency - 50 Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(kong_request_latency_ms_bucket{service=~\"${api}\"}[5m])) by (service,le))",
       "legendFormat": "p50-{{api}}"
      }
     ]
    },
    {
     "title": "Upstream Latency - 50 Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(kong_upstream_latency_ms_bucket{service=~\"${api}\"}[5m])) by (service,le))",
       "legendFormat": "p50-{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request / Response Size - Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Request Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_bandwidth_bytes{service=~\"${api}\",direction=\"ingress\"}[5m])) by (service) / sum(rate(kong_http_requests_total{service=~\"${api}\"}[5m])) by (service)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Average Response Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_bandwidth_bytes{service=~\"${api}\",direction=\"egress\"}[5m])) by (service) / sum(rate(kong_http_requests_total{service=~\"${api}\"}[5m])) by (service)",
       "legendFormat": "{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request / Response Size - Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Bandwidth (bytes/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_bandwidth_bytes{service=~\"${api}\",direction=\"ingress\"}[5m])) by (service)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Response Bandwidth (bytes/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_bandwidth_bytes{service=~\"${api}\",direction=\"egress\"}[5m])) by (service)",
       "legendFormat": "{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apdex Score (Threshold of 50ms)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_request_latency_ms_bucket{service=~\"${api}\", le=\"50\"}[5m])) by (service) / sum(rate(kong_request_latency_ms_count{service=~\"${api}\"}[5m])) by (service)",
       "legendFormat": "{{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests / API",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_http_requests_total{consumer=~\"${username}\",service=~\"$api\"}[$__range])) by (service)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Total Requests / Username",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_http_requests_total{consumer=~\"${username}\",service=~\"${api}\"}[$__range])) by (consumer)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Requests per sec / API",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_requests_total{consumer=~\"${username}\",service=~\"${api}\"}[1m])) by (service)",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "Requests per sec / User",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_requests_total{consumer=~\"${username}\",service=~\"${api}\"}[1m])) by (consumer)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Success %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_http_requests_total{consumer=~\"${username}\",service=~\"${api}\",code=~\"2..|3..\"}[1m])) by (service, code) / ignoring(code) group_left sum(increase(kong_http_requests_total{consumer=~\"${username}\",service=~\"${api}\"}[1m])) by (service)",
       "legendFormat": "{{api}}-{{status}}"
      }
     ]
    },
    {
     "title": "Error %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code!~\"2..|3..\"}[1m])) by (service, code) / ignoring(code) group_left  sum(increase(kong_http_requests_total{service=~\"${api}\"}[1m])) by (service)",
       "legendFormat": "{{api}}-{{status_code}}"
      }
     ]
    },
    {
     "title": "Success Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code=~\"2..|3..\"}[1m])) by (service, code)",
       "legendFormat": "{{api}}-{{status}}"
      }
     ]
    },
    {
     "title": "Error Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kong_http_requests_total{service=~\"${api}\",code!~\"2..|3..\"}[1m])) by (service, code)",
       "legendFormat": "{{api}}-{{status}}"
      }
     ]
    }
   ]
  }
 ]
}