{
 "title": "Envoy Global",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(envoy_cluster_upstream_cx_total, envoy_cluster_name)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$cluster\", job=~\"$job\"}, instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Envoy Global — Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live servers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "sum(envoy_server_live)" }
     ]
    },
    {
     "title": "Avg uptime per node",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "avg(envoy_server_uptime)" }
     ]
    },
    {
     "title": "Allocated Memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "SUM(envoy_server_memory_allocated)"
      }
     ]
    },
    {
     "title": "Heap Size",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 14, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "SUM(envoy_server_memory_heap_size)"
      }
     ]
    },
    {
     "title": "Unhealthy Clusters",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(sum(envoy_cluster_membership_healthy)  - sum(envoy_cluster_membership_total))"
      }
     ]
    },
    {
     "title": "Cluster State",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(sum(envoy_cluster_membership_total)-sum(envoy_cluster_membership_healthy)) == bool 0"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))",
       "legendFormat": "Globlal RPS"
      },
      {
       "expr": "sum(rate(envoy_cluster_health_check_attempt[1m]))",
       "legendFormat": "Global HC RPS"
      },
      {
       "expr": "sum(rate(envoy_http_rq_total[1m]))",
       "legendFormat": "Global Routed RPS"
      }
     ]
    },
    {
     "title": "Global CPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
       "legendFormat": "Global CPS"
      }
     ]
    },
    {
     "title": "Success Rate (non-5xx responses)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(1 - (sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx[1m]))))",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(envoy_http_downstream_cx_active)",
       "legendFormat": "Global Connections"
      },
      {
       "expr": "sum(envoy_server_parent_connections)",
       "legendFormat": "Global Parent Connections"
      }
     ]
    },
    {
     "title": "Upstream failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject[1m]))",
       "legendFormat": "Pending failure ejection"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow[1m]))",
       "legendFormat": "Pending Overflow"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m]))",
       "legendFormat": "Connect Timeout"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m]))",
       "legendFormat": "Request Timeout"
      }
     ]
    },
    {
     "title": "Upstream Retries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))",
       "legendFormat": "Retry"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m]))",
       "legendFormat": "Retry Success"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m]))",
       "legendFormat": "Retry Overflow"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy Proxy — Traffic Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / Sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "2xx Success %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"3..|4..|5..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
       "legendFormat": "{{job}} - {{envoy_response_code}}"
      }
     ]
    },
    {
     "title": "5xx Failures %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"2..|3..|4..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, instance, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, instance)",
       "legendFormat": "{{job}} - {{envoy_response_code}}"
      }
     ]
    },
    {
     "title": "3xx Success %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"2..|4..|5..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
       "legendFormat": "{{job}} - {{envoy_response_code}}"
      }
     ]
    },
    {
     "title": "4xx Failures %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq{envoy_response_code!~\"2..|3..|5..\",envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job, envoy_response_code) / ignoring(envoy_response_code) group_left sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by(job)",
       "legendFormat": "{{job}} - {{envoy_response_code}}"
      }
     ]
    },
    {
     "title": "Total active connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[$__range])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy Proxy — Upstream Connections and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (le,job))",
       "legendFormat": "{{job}} - 50th %ile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (le, job))",
       "legendFormat": "{{job}} - 95th %ile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (le,job))",
       "legendFormat": "{{job}} - 99th %ile"
      }
     ]
    },
    {
     "title": "Upstream Request Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - connect timeout"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - pending failure ejection"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - pending overflow"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - request timeout"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - per try request timeout"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - request reset"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - destroy initialized from originating service"
      },
      {
       "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - destroy initialized from remote service"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[1m])) by (job)",
       "legendFormat": "{{job}} - request failed maintenance mode"
      }
     ]
    },
    {
     "title": "Upstream Total active connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Upstream members",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job) / count(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - healthy"
      },
      {
       "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job) / count(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (job)",
       "legendFormat": "{{job}} - total"
      }
     ]
    },
    {
     "title": "Upstream Network Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - in"
      },
      {
       "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - out"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy Proxy — Downstream Connections and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downstream Total active connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}} - ingress_http"
      },
      {
       "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{job}} - admin"
      }
     ]
    },
    {
     "title": "Downstream Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - in (ingress_http)"
      },
      {
       "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - out (ingress_http)"
      },
      {
       "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - in (admin)"
      },
      {
       "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - out (admin)"
      }
     ]
    },
    {
     "title": "Downstream Total active requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"ingress_http\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - ingress_http"
      },
      {
       "expr": "irate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"admin\",job=~\"$job\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{job}} - admin"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Policy Agent — Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (job) / sum(rate(http_request_duration_seconds_count{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "HTTP Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
       "legendFormat": "50th Quantile (Median) - {{job}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
       "legendFormat": "90th Quantile - {{job}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
       "legendFormat": "95th Quantile - {{job}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\", namespace=\"$namespace\"}[$interval])) by (le, job))",
       "legendFormat": "99th Quantile - {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Policy Agent — Object and Pointers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Live Objects",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", job=~\"$job\"} - go_memstats_frees_total{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences per $interval",
     "type": "graph",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated Per $interval",
     "type": "graph",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation per $interval",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - stack allocator"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - system stack allocator"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Policy Agent — Memory In Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes allocated & still in-use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes waiting to be used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes in use ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes released to OS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Objects allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Policy Agent — Memory Off-heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Runtime Memory Info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mspan"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mspan system"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mcache"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - mcache system"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - profiling bucket hash table"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - garbage collection system metadata"
      },
      {
       "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - other system allocations"
      },
      {
       "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - next garbage collection"
      }
     ]
    },
    {
     "title": "Mspan bytes usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for mspan obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for mcache obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes in use by mcache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for garbage collection system metadata",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used by the profiling bucket hash table",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes when next garbage collection will take place",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bytes used for other system allocations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - bytes of memory are used for other runtime allocations"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{job}} - quantile {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}