{
 "title": "Secor Consumer Lag and kafka topics details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "dev" }
  ]
 },
 "panels": [
  {
   "title": "Topics partition count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=~\"$env.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics current offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=~\"$env.*\"}",
     "legendFormat": "{{topic}}::{{partition}}"
    }
   ]
  },
  {
   "title": "Logstash Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "logstash Raw events lag",
     "type": "stat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=~\"ntpprod.flink.kp.events\", job=\"ingestion-kafka-exporter\"})"
      }
     ]
    },
    {
     "title": "logstash Telemetry Error events lag",
     "type": "stat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=~\"ntpprod.telemetry-log.indexer\", job=\"processing-kafka-exporter\", topic=\"ntpprod.druid.events.error\"})"
      }
     ]
    },
    {
     "title": "logstash Telemetry log events lag",
     "type": "stat",
     "description": "Threshold:\nWarning: 1M\nCritical:  2M",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(partition) (kafka_consumergroup_lag{consumergroup=~\"ntpprod.telemetry-log.indexer\", job=\"processing-kafka-exporter\", topic=\"ntpprod.druid.events.log\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "telemetry-ingest-backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "telemetry-ingest-backup lag",
     "type": "stat",
     "description": "Threshold: \nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumergroup_lag_sum{consumergroup=~\"$env-telemetry-ingest-backup\", job=\"kafka-exporter\"}",
       "legendFormat": "telemetry-ingest-backup"
      }
     ]
    },
    {
     "title": "telemetry-ingest-backup process count",
     "type": "stat",
     "description": "Threshold: \nWarning: 10M\nCritical: 15M",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=\"telemetry-ingest-backup\"})",
       "legendFormat": "telemetry-ingest-backup"
      }
     ]
    }
   ]
  }
 ]
}