{
 "title": "Service memory usage",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "player_player",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"player_player\"})"
    }
   ]
  },
  {
   "title": "knowlg-service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"knowlg-service\"})"
    }
   ]
  },
  {
   "title": "userorg-service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"userorg-service\"})"
    }
   ]
  },
  {
   "title": "telemetry-service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"telemetry-service\"})"
    }
   ]
  },
  {
   "title": "telemetry-logstash",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"telemetry-logstash\"})"
    }
   ]
  },
  {
   "title": "Prometheus_DS1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"Prometheus_DS1\"})"
    }
   ]
  },
  {
   "title": "logger_kibana",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"logger_kibana\"})"
    }
   ]
  },
  {
   "title": "proxy_proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"proxy_proxy\"})"
    }
   ]
  },
  {
   "title": "api-manager_kong",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"api-manager_kong\"})"
    }
   ]
  },
  {
   "title": "api-manager_echo",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"api-manager_echo\"})"
    }
   ]
  },
  {
   "title": "logger_logspout",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"logger_logspout\"})"
    }
   ]
  },
  {
   "title": "monitor_logstash",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"monitor_logstash\"})"
    }
   ]
  },
  {
   "title": "logger_logstash",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"logger_logstash\"})"
    }
   ]
  },
  {
   "title": "monitor_cadvisor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"monitor_cadvisor\"})"
    }
   ]
  }
 ]
}