{
 "title": "Weekly Report Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(container_last_seen, container_label_com_docker_swarm_service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily Peak of Request per Second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Daily Peaks of Request per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  { "title": "Max % HTTP 4xx Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Max % HTTP 4xx Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|5..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Max % HTTP 5xx Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{status!~\"2..|3..|4..\"}[5m])) by (status) / ignoring(status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "API Requests Error %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "4xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(kong_http_requests_total{code!~\"2..|3..|5..\"}[5m])) by (service, code) / ignoring(service, code) group_left sum(increase(kong_http_requests_total[5m])))",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(kong_http_requests_total{code!~\"2..|3..|4..\"}[5m])) by (service, code) / ignoring(service, code) group_left sum(increase(kong_http_requests_total[5m])))",
     "legendFormat": "{{api}}-{{status_code}}"
    }
   ]
  },
  { "title": "Load Avg on VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Load avg on VMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(host) * on (instance) group_left(nodename) node_load1",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(node_load1) * on (instance) group_left(nodename) node_uname_info{job=~\".*node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Load Avg of Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{image!=\"\", container_label_com_docker_swarm_service_name=~\"$service\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Top 10 API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Top 10 API Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(kong_http_requests_total[5m])",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "APIs Avg/Min/Max Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "APIs Average/Min/Max Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "kong_request_latency_ms", "legendFormat": "{{api}}" }
   ]
  }
 ]
}