{
 "title": "YugabyteDB",
 "description": "Monitor YugabyteDB",
 "tags": [
  "YugabyteDB",
  "yugabytedb",
  "ysql",
  "ycql",
  "yedis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "dbcluster", "label": "YugabyteDB Cluster", "query": "label_values(node_prefix)" },
   {
    "name": "master_node",
    "query": "label_values(up{node_prefix=\"$dbcluster\", export_type=\"master_export\"}, instance)"
   },
   {
    "name": "tserver_node",
    "query": "label_values(up{node_prefix=\"$dbcluster\", export_type=\"tserver_export\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Master Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Master Status - $master_node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "master_node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{node_prefix=\"$dbcluster\",instance=~\"${master_node}\"})"
    }
   ]
  },
  { "title": "TServer Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "TServer Status - $tserver_node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "repeat": "tserver_node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{node_prefix=\"$dbcluster\",instance=~\"${tserver_node}\"})"
    }
   ]
  },
  { "title": "YSQL Ops & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total YSQL Ops / Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count\"}[5m]))",
     "legendFormat": "Select"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count\"}[5m]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count\"}[5m]))",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count\"}[5m]))",
     "legendFormat": "Transaction"
    }
   ]
  },
  {
   "title": "YSQL Op Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count\"}[5m]))\r",
     "legendFormat": "Select"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count\"}[5m]))\r",
     "legendFormat": "Insert"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))\r",
     "legendFormat": "Update"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))\r",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count\"}[5m]))\r",
     "legendFormat": "Other"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_Transactions_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count\"}[5m]))\r",
     "legendFormat": "Transaction"
    }
   ]
  },
  {
   "title": "Select - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Select - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance)(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_sum\"}[5m])) / avg by (exported_instance)(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Insert - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Insert - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Update - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Update - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Delete - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Delete - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Others - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Others - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Transactions - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Transactions - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_Transactions_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(threads_running{node_prefix=\"$dbcluster\",export_type=\"master_export\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "avg(threads_started{node_prefix=\"$dbcluster\",export_type=\"master_export\"})",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Master Log Ops / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_sync_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "Total Avg - Sync"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_group_commit_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "Total Avg - Commit"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_append_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "Total Avg  - Append"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_sync_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Sync"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_group_commit_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Commit"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_append_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Append"
    }
   ]
  },
  {
   "title": "Master Log Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(log_sync_latency_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])) / avg(irate(log_sync_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))",
     "legendFormat": "Sync"
    },
    {
     "expr": "avg(irate(log_group_commit_latency_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])) / avg(irate(log_group_commit_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))",
     "legendFormat": "Commit"
    },
    {
     "expr": "avg(irate(log_append_latency_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])) / avg(irate(log_append_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))",
     "legendFormat": "Append"
    }
   ]
  },
  {
   "title": "Log Stats / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"master_export\"})) / 1024",
     "legendFormat": "Total Avg - Log Bytes Read"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (log_cache_size{node_prefix=\"$dbcluster\",export_type=\"master_export\"})) / 1024",
     "legendFormat": "Total Avg - Log Cache Size"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"master_export\"})) / 1024",
     "legendFormat": "{{exported_instance}} - Log Bytes Read"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_size{node_prefix=\"$dbcluster\",export_type=\"master_export\"})) / 1024",
     "legendFormat": "{{exported_instance}} - Log Cache Size"
    }
   ]
  },
  {
   "title": "Log Bytes Written / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_bytes_logged{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "Total Avg - Log Bytes Logged"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_bytes_logged{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Log Bytes Logged"
    }
   ]
  },
  {
   "title": "Glog messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(glog_info_messages{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(rate(glog_warning_messages{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(rate(glog_error_messages{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Log Bytes Read / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "Total Avg - Log Bytes Read"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Log Bytes Read"
    }
   ]
  },
  {
   "title": "RPC queue sizes (Master)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rpcs_in_queue_yb_master_MasterService{node_prefix=\"$dbcluster\"})",
     "legendFormat": "Master RPC"
    }
   ]
  },
  {
   "title": "Log Cache Num Ops / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (log_cache_num_ops{node_prefix=\"$dbcluster\",export_type=\"master_export\"}))",
     "legendFormat": "Total Avg - Num Ops"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_num_ops{node_prefix=\"$dbcluster\",export_type=\"master_export\"})) / 1024",
     "legendFormat": "{{exported_instance}} - Num Ops"
    }
   ]
  },
  {
   "title": "Total Ops / Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_count\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_count\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Op / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}} - Write"
    },
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}} - Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_count\"}[5m]))\r",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"master_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_count\"}[5m]))\r",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Reactor Delays",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_incoming_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))\r",
     "legendFormat": "Incoming Queue"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_transfer_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))\r",
     "legendFormat": "Outbound transfer time"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"master_export\"}[5m]))\r",
     "legendFormat": "Outbound queue time"
    }
   ]
  },
  { "title": "YCQL Ops & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Total YCQL Ops / Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count\"}[5m]))",
     "legendFormat": "Select"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count\"}[5m]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count\"}[5m]))",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_count\"}[5m]))",
     "legendFormat": "Transaction"
    }
   ]
  },
  {
   "title": "YCQL Op Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count\"}[5m]))\r",
     "legendFormat": "Select"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count\"}[5m]))\r",
     "legendFormat": "Insert"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))\r",
     "legendFormat": "Update"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))\r",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count\"}[5m]))\r",
     "legendFormat": "Other"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_count\"}[5m]))\r",
     "legendFormat": "Transaction"
    }
   ]
  },
  {
   "title": "YCQL Op Latency (P95)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p95\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt\"})",
     "legendFormat": "Select"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p95\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt\"})",
     "legendFormat": "Insert"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p95\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt\"})",
     "legendFormat": "Update"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p95\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p95\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts\"})",
     "legendFormat": "Other"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p95\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction\"})",
     "legendFormat": "Transaction"
    }
   ]
  },
  {
   "title": "YCQL Op Latency (P99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p99\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt\"})",
     "legendFormat": "Select"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p99\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt\"})",
     "legendFormat": "Insert"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p99\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt\"})",
     "legendFormat": "Update"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p99\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p99\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts\"})",
     "legendFormat": "Other"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\", quantile=\"p99\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction\"})",
     "legendFormat": "Transaction"
    }
   ]
  },
  {
   "title": "Select - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Select - Op Latency (Avg) /  Tserver",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_SelectStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Update - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Update - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_UpdateStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Delete - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Delete - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_DeleteStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Insert - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Insert - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_InsertStmt_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Others - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 191 },
   "repeat": "tserver",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Others - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 191 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_OtherStmts_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_count\"}[5m]))\r",
     "legendFormat": "Transaction"
    }
   ]
  },
  {
   "title": "Transaction - Op / Sec / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_count\"}[5m]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Transaction - Op Latency (Avg) / TServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_Transaction_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Reactor Delays",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_incoming_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"cql_export\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"cql_export\"}[5m]))\r",
     "legendFormat": "Incoming Queue"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_transfer_sum{node_prefix=\"$dbcluster\",export_type=\"cql_export\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{node_prefix=\"$dbcluster\",export_type=\"cql_export\"}[5m]))\r",
     "legendFormat": "Outbound transfer time"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"cql_export\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"cql_export\"}[5m]))\r",
     "legendFormat": "Outbound queue time"
    }
   ]
  },
  {
   "title": "YCQL Inbound Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_connections_alive{node_prefix=\"$dbcluster\",metric_id=\"yb.cqlserver\"}[5m]))",
     "legendFormat": "Connections Alive"
    }
   ]
  },
  {
   "title": "YCQL Latency Breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_ProcessRequest_sum\"}[5m])) / sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_ProcessRequest_count\"}[5m]))\r",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_ParseRequest_sum\"}[5m])) / sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_ParseRequest_count\"}[5m]))\r",
     "legendFormat": "Parse"
    },
    {
     "expr": "sum(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_AnalyzeRequest_sum\"}[5m])) / sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_AnalyzeRequest_count\"}[5m]))\r",
     "legendFormat": "Analyze"
    },
    {
     "expr": "sum(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_ExecuteRequest_sum\"}[5m])) / sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_CQLServerService_ExecuteRequest_count\"}[5m]))\r",
     "legendFormat": "Execute"
    }
   ]
  },
  {
   "title": "Response Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_ResponseSize_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_cqlserver_SQLProcessor_ResponseSize_count\"}[5m]))\r",
     "legendFormat": "Response Size"
    }
   ]
  },
  {
   "title": "RPC queue sizes (YCQL)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rpcs_in_queue_yb_cqlserver_CQLServerService{node_prefix=\"$dbcluster\"})",
     "legendFormat": "YCQL RPC - Max"
    },
    {
     "expr": "rpcs_in_queue_yb_cqlserver_CQLServerService{node_prefix=\"$dbcluster\"}",
     "legendFormat": "YCQL RPC - {{exported_instance}}"
    }
   ]
  },
  { "title": "Tablet Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 236 } },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_count\"}[5m]))\r",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_count\"}[5m]))\r",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Reactor Delays",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 237 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_incoming_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))\r",
     "legendFormat": "Incoming Queue"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_transfer_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))\r",
     "legendFormat": "Outbound transfer time"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))\r",
     "legendFormat": "Outbound queue time"
    }
   ]
  },
  {
   "title": "Total Ops / Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 246 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_count\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_count\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Op / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 246 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Write_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}} - Write"
    },
    {
     "expr": "avg by (exported_instance) (irate(rpc_latency_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_sum\"}[5m])) / avg by (exported_instance) (irate(rpc_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\",saved_name=\"handler_latency_yb_tserver_TabletServerService_Read_count\"}[5m]))\r",
     "legendFormat": "{{exported_instance}} - Read"
    }
   ]
  },
  {
   "title": "Consensus Ops / Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 255 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_UpdateConsensus_sum\"}[5m])) / sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_UpdateConsensus_count\"}[5m]))\r",
     "legendFormat": "UpdateConsensus"
    },
    {
     "expr": "sum(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_sum\"}[5m])) / sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_count\"}[5m]))\r",
     "legendFormat": "RequestConsensusVote"
    }
   ]
  },
  {
   "title": "Total Consensus Change Config",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 255 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rpc_latency{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_ChangeConfig\"})",
     "legendFormat": "ChangeConfig"
    },
    {
     "expr": "sum(rpc_latency{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_RunLeaderElection\"})",
     "legendFormat": "RunLeaderElection"
    },
    {
     "expr": "sum(rpc_latency{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_LeaderStepDown\"})",
     "legendFormat": "LeaderStepDown"
    },
    {
     "expr": "sum(rpc_latency{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_LeaderElectionLost\"})",
     "legendFormat": "LeaderElectionLost"
    }
   ]
  },
  {
   "title": "Remote Bootstraps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 264 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rpc_latency{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_StartRemoteBootstrap\"})",
     "legendFormat": "remote bootstraps"
    }
   ]
  },
  {
   "title": "Consensus RPC Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 264 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_UpdateConsensus_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_UpdateConsensus_count\"}[5m]))\r",
     "legendFormat": "UpdateConsensus"
    },
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_RequestConsensusVote_count\"}[5m]))\r",
     "legendFormat": "RequestConsensusVote"
    }
   ]
  },
  {
   "title": "Change Config Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 273 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_ChangeConfig_sum\"}[5m])) / avg(irate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_consensus_ConsensusService_ChangeConfig_count\"}[5m]))\r",
     "legendFormat": "ChangeConfig"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 273 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(threads_running{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "avg(threads_started{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 282 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(involuntary_context_switches{node_prefix=\"$dbcluster\"}[5m]))",
     "legendFormat": "Involuntary"
    },
    {
     "expr": "avg(irate(voluntary_context_switches{node_prefix=\"$dbcluster\"}[5m]))",
     "legendFormat": "Voluntary"
    }
   ]
  },
  {
   "title": "SpinLock Time/Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 282 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(spinlock_contention_time{node_prefix=\"$dbcluster\"}[5m])) / 1000000",
     "legendFormat": "SpinLock"
    }
   ]
  },
  {
   "title": "TServer Log Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 291 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(log_sync_latency_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])) / avg(irate(log_sync_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))",
     "legendFormat": "Sync"
    },
    {
     "expr": "avg(irate(log_group_commit_latency_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])) / avg(irate(log_group_commit_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))",
     "legendFormat": "Commit"
    },
    {
     "expr": "avg(irate(log_append_latency_sum{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])) / avg(irate(log_append_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))",
     "legendFormat": "Append"
    }
   ]
  },
  {
   "title": "Log Bytes Written / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 291 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_bytes_logged{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "Total Avg - Log Bytes Logged"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_bytes_logged{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Log Bytes Logged"
    }
   ]
  },
  {
   "title": "Log Bytes Read / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 300 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "Total Avg - Log Bytes Read"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Log Bytes Read"
    }
   ]
  },
  {
   "title": "TServer Log Ops / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 300 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_sync_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "Total Avg - Sync"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_group_commit_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "Total Avg - Commit"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(log_append_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "Total Avg  - Append"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_sync_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Sync"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_group_commit_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Commit"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (rate(log_append_latency_count{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m])))",
     "legendFormat": "{{exported_instance}} - Append"
    }
   ]
  },
  {
   "title": "TServer TCMalloc Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 309 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(generic_current_allocated_bytes{node_prefix=\"$dbcluster\"}) / 1048576",
     "legendFormat": "In Use"
    },
    {
     "expr": "avg(generic_heap_size{node_prefix=\"$dbcluster\"}) / 1048576",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Log Stats / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 309 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})) / 1024",
     "legendFormat": "Total Avg - Log Bytes Read"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (log_cache_size{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})) / 1024",
     "legendFormat": "Total Avg - Log Cache Size"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_reader_bytes_read{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})) / 1024",
     "legendFormat": "{{exported_instance}} - Log Bytes Read"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_size{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})) / 1024",
     "legendFormat": "{{exported_instance}} - Log Cache Size"
    }
   ]
  },
  {
   "title": "Log Cache Num Ops / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 318 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (log_cache_num_ops{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}))",
     "legendFormat": "Total Avg - Num Ops"
    },
    {
     "expr": "avg by (exported_instance) (sum without (table_id, table_name) (log_cache_num_ops{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})) / 1024",
     "legendFormat": "{{exported_instance}} - Num Ops"
    }
   ]
  },
  {
   "title": "Glog messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 318 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(glog_info_messages{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(rate(glog_warning_messages{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(rate(glog_error_messages{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "RPC queue sizes (Tserver)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 327 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rpcs_in_queue_yb_consensus_ConsensusService{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "Consensus"
    },
    {
     "expr": "max(rpcs_in_queue_yb_server_GenericService{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "Generic"
    },
    {
     "expr": "max(rpcs_in_queue_yb_tserver_RemoteBootstrapService{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "RemoteBootstrap"
    },
    {
     "expr": "max(rpcs_in_queue_yb_tserver_TabletServerService{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "TS RPC"
    },
    {
     "expr": "max(rpcs_in_queue_yb_tserver_TabletServerBackupService{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "Backups"
    },
    {
     "expr": "max(rpcs_in_queue_yb_tserver_TabletServerAdminService{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "Admin"
    },
    {
     "expr": "max(rpcs_in_queue_yb_cdc_CDCService{node_prefix=\"$dbcluster\",export_type=\"tserver_export\"})",
     "legendFormat": "CDC"
    }
   ]
  },
  { "title": "RocksDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 336 } },
  {
   "title": "LSM-DB Seek/Next Num Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 337 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_number_db_seek{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Seek"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_number_db_next{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Next"
    }
   ]
  },
  {
   "title": "LSM-DB Seeks / Sec / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 337 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_number_db_seek{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Seek"
    }
   ]
  },
  {
   "title": "SSTable size / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 346 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rocksdb_current_version_sst_files_size{node_prefix=\"$dbcluster\"})) / 1073741824",
     "legendFormat": "Size of SSTables"
    }
   ]
  },
  {
   "title": "Average SSTables / Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 346 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rocksdb_current_version_num_sst_files{node_prefix=\"$dbcluster\"}))",
     "legendFormat": "Average SSTables / Node"
    }
   ]
  },
  {
   "title": "LSM-DB Blooms usefulness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 355 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_bloom_filter_checked{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Blooms checked"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_bloom_filter_useful{node_prefix=\"$dbcluster\"}[5m]))) ",
     "legendFormat": "Blooms useful"
    }
   ]
  },
  {
   "title": "LSM-DB Get Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 355 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_get_micros_sum{node_prefix=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (rate(rocksdb_db_get_micros_count{node_prefix=\"$dbcluster\"}[5m]))\r)",
     "legendFormat": "Get"
    }
   ]
  },
  {
   "title": "LSM-DB Write Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 364 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_write_micros_sum{node_prefix=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (rate(rocksdb_db_write_micros_count{node_prefix=\"$dbcluster\"}[5m]))\r)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "LSM-DB Seek Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 364 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_seek_micros_sum{node_prefix=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (rate(rocksdb_db_seek_micros_count{node_prefix=\"$dbcluster\"}[5m]))\r)",
     "legendFormat": "Seek "
    }
   ]
  },
  {
   "title": "LSM-DB Mutex Wait Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 373 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_db_mutex_wait_micros{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Mutex"
    }
   ]
  },
  {
   "title": "Cache Hit & Miss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 373 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_hit{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Hit"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_miss{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Block cache usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 382 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "avg(block_cache_single_touch_usage{node_prefix=\"$dbcluster\"}) / 1073741824",
     "legendFormat": "Single Touch"
    },
    {
     "expr": "avg(block_cache_multi_touch_usage{node_prefix=\"$dbcluster\"}) / 1073741824",
     "legendFormat": "Multi Touch"
    }
   ]
  },
  {
   "title": "Cache Add",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 382 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_add{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Add"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_single_touch_add{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Single Touch Add"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_block_cache_multi_touch_add{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Multi Touch Add"
    }
   ]
  },
  {
   "title": "Stalls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 391 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_stall_micros{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Stalls"
    }
   ]
  },
  {
   "title": "Rejections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 391 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(majority_sst_files_rejections{node_prefix=\"$dbcluster\"}[5m])))",
     "legendFormat": "Rejections"
    }
   ]
  },
  {
   "title": "Flush write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 400 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_flush_write_bytes{node_prefix=\"$dbcluster\"}[5m]))) / 1048576",
     "legendFormat": "Flush"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 400 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_compact_read_bytes{node_prefix=\"$dbcluster\"}[5m]))) / 1048576",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "avg(sum without (table_id, table_name) (rate(rocksdb_compact_write_bytes{node_prefix=\"$dbcluster\"}[5m]))) / 1048576",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  {
   "title": "Compaction num files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 409 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (irate(rocksdb_numfiles_in_singlecompaction_sum{node_prefix=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (irate(rocksdb_numfiles_in_singlecompaction_count{node_prefix=\"$dbcluster\"}[5m]))\r)",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Compaction time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 409 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(sum without (table_id, table_name) (irate(rocksdb_compaction_times_micros_sum{node_prefix=\"$dbcluster\"}[5m]))) / avg(sum without (table_id, table_name) (irate(rocksdb_compaction_times_micros_count{node_prefix=\"$dbcluster\"}[5m]))\r)",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "YEDIS Ops & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 418 } },
  {
   "title": "Total YEDIS Ops / Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 419 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get_count\"}[5m]))\r",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget_count\"}[5m]))\r",
     "legendFormat": "MGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))\r",
     "legendFormat": "StrLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists_count\"}[5m]))\r",
     "legendFormat": "Exists"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange_count\"}[5m]))\r",
     "legendFormat": "GetRange"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set_count\"}[5m]))\r",
     "legendFormat": "Set"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset_count\"}[5m]))\r",
     "legendFormat": "MSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset_count\"}[5m]))\r",
     "legendFormat": "GetSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append_count\"}[5m]))\r",
     "legendFormat": "Append"
    },
    {
     "expr": " sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del_count\"}[5m]))\r",
     "legendFormat": "Del"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange_count\"}[5m]))\r",
     "legendFormat": "SetRange"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr_count\"}[5m]))\r",
     "legendFormat": "Incr"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget_count\"}[5m]))",
     "legendFormat": "TsGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd_count\"}[5m]))",
     "legendFormat": "TsAdd"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count\"}[5m]))",
     "legendFormat": "TsRangeByTime"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem_count\"}[5m]))",
     "legendFormat": "TsRem"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers_count\"}[5m]))",
     "legendFormat": "SMembers"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember_count\"}[5m]))",
     "legendFormat": "SIsMember"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard_count\"}[5m]))",
     "legendFormat": "SCard"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))",
     "legendFormat": "StrLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd_count\"}[5m]))",
     "legendFormat": "SAdd"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem_count\"}[5m]))",
     "legendFormat": "SRem"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo_count\"}[5m]))\r",
     "legendFormat": "Echo"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth_count\"}[5m]))\r",
     "legendFormat": "Auth"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config_count\"}[5m]))\r",
     "legendFormat": "Config"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info_count\"}[5m]))\r",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role_count\"}[5m]))\r",
     "legendFormat": "Role"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping_count\"}[5m]))\r",
     "legendFormat": "Ping"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit_count\"}[5m]))\r",
     "legendFormat": "Quit"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb_count\"}[5m]))\r",
     "legendFormat": "FlushDB"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command_count\"}[5m]))\r",
     "legendFormat": "Command"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget_count\"}[5m]))\r",
     "legendFormat": "HGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget_count\"}[5m]))\r",
     "legendFormat": "HMGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall_count\"}[5m]))\r",
     "legendFormat": "HGetAll"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys_count\"}[5m]))\r",
     "legendFormat": "HKeys"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals_count\"}[5m]))\r",
     "legendFormat": "HVals"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen_count\"}[5m]))\r",
     "legendFormat": "HLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists_count\"}[5m]))\r",
     "legendFormat": "HExists"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen_count\"}[5m]))\r",
     "legendFormat": "HStrLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset_count\"}[5m]))\r",
     "legendFormat": "HSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset_count\"}[5m]))\r",
     "legendFormat": "HMSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel_count\"}[5m]))\r",
     "legendFormat": "HDel"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby_count\"}[5m]))\r",
     "legendFormat": "HIncrBy"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 419 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get_count\"}[5m]))",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget_count\"}[5m]))\r",
     "legendFormat": "MGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))\r",
     "legendFormat": "StrLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists_count\"}[5m]))\r",
     "legendFormat": "Exists"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange_count\"}[5m]))\r",
     "legendFormat": "GetRange"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set_count\"}[5m]))\r",
     "legendFormat": "Set"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset_count\"}[5m]))\r",
     "legendFormat": "MSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset_count\"}[5m]))\r",
     "legendFormat": "GetSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append_count\"}[5m]))\r",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del_count\"}[5m]))\r",
     "legendFormat": "Del"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange_count\"}[5m]))\r",
     "legendFormat": "SetRange"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr_count\"}[5m]))\r",
     "legendFormat": "Incr"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget_count\"}[5m]))",
     "legendFormat": "TsGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd_count\"}[5m]))",
     "legendFormat": "TsAdd"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count\"}[5m]))",
     "legendFormat": "TsRangeByTime"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem_count\"}[5m]))",
     "legendFormat": "TsRem"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers_count\"}[5m]))",
     "legendFormat": "SMembers"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember_count\"}[5m]))",
     "legendFormat": "SIsMember"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard_count\"}[5m]))",
     "legendFormat": "SCard"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))",
     "legendFormat": "StrLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd_count\"}[5m]))",
     "legendFormat": "SAdd"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem_count\"}[5m]))",
     "legendFormat": "SRem"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo_count\"}[5m]))\r",
     "legendFormat": "Echo"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth_count\"}[5m]))\r",
     "legendFormat": "Auth"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config_count\"}[5m]))\r",
     "legendFormat": "Config"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info_count\"}[5m]))\r",
     "legendFormat": "Info"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role_count\"}[5m]))\r",
     "legendFormat": "Role"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping_count\"}[5m]))\r",
     "legendFormat": "Ping"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit_count\"}[5m]))\r",
     "legendFormat": "Quit"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb_sum\"}[5m])) /avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb_count\"}[5m]))\r",
     "legendFormat": "FlushDB"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command_count\"}[5m]))\r",
     "legendFormat": "Command"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget_count\"}[5m]))\r",
     "legendFormat": "HGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget_count\"}[5m]))\r",
     "legendFormat": "HMGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall_count\"}[5m]))\r",
     "legendFormat": "HGetAll"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys_count\"}[5m]))\r",
     "legendFormat": "HKeys"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals_count\"}[5m]))\r",
     "legendFormat": "HVals"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen_count\"}[5m]))\r",
     "legendFormat": "HLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists_count\"}[5m]))\r",
     "legendFormat": "HExists"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen_count\"}[5m]))\r",
     "legendFormat": "HStrLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset_count\"}[5m]))\r",
     "legendFormat": "HSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset_count\"}[5m]))\r",
     "legendFormat": "HMSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel_count\"}[5m]))\r",
     "legendFormat": "HDel"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby_count\"}[5m]))\r",
     "legendFormat": "HIncrBy"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency (P95)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 428 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget\"})\r",
     "legendFormat": "MGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen\"})\r",
     "legendFormat": "StrLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists\"})\r",
     "legendFormat": "Exists"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange\"})\r",
     "legendFormat": "GetRange"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set\"})\r",
     "legendFormat": "Set"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset\"})\r",
     "legendFormat": "MSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset\"})\r",
     "legendFormat": "GetSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append\"})\r",
     "legendFormat": "Append"
    },
    {
     "expr": " max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del\"})\r",
     "legendFormat": "Del"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange\"})\r",
     "legendFormat": "SetRange"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr\"})\r",
     "legendFormat": "Incr"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget\"})",
     "legendFormat": "TsGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd\"})",
     "legendFormat": "TsAdd"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime\"})",
     "legendFormat": "TsRangeByTime"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem\"})",
     "legendFormat": "TsRem"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers\"})",
     "legendFormat": "SMembers"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember\"})",
     "legendFormat": "SIsMember"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard\"})",
     "legendFormat": "SCard"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen\"})",
     "legendFormat": "StrLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd\"})",
     "legendFormat": "SAdd"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem\"})",
     "legendFormat": "SRem"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo\"})\r",
     "legendFormat": "Echo"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth\"})\r",
     "legendFormat": "Auth"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config\"})\r",
     "legendFormat": "Config"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info\"})\r",
     "legendFormat": "Info"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role\"})\r",
     "legendFormat": "Role"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping\"})\r",
     "legendFormat": "Ping"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit\"})\r",
     "legendFormat": "Quit"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb\"})\r",
     "legendFormat": "FlushDB"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command\"})\r",
     "legendFormat": "Command"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget\"})\r",
     "legendFormat": "HGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget\"})\r",
     "legendFormat": "HMGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall\"})\r",
     "legendFormat": "HGetAll"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys\"})\r",
     "legendFormat": "HKeys"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals\"})\r",
     "legendFormat": "HVals"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen\"})\r",
     "legendFormat": "HLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists\"})\r",
     "legendFormat": "HExists"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen\"})\r",
     "legendFormat": "HStrLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset\"})\r",
     "legendFormat": "HSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset\"})\r",
     "legendFormat": "HMSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel\"})\r",
     "legendFormat": "HDel"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p95\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby\"})\r",
     "legendFormat": "HIncrBy"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency (P99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 428 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget\"})\r",
     "legendFormat": "MGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen\"})\r",
     "legendFormat": "StrLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists\"})\r",
     "legendFormat": "Exists"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange\"})\r",
     "legendFormat": "GetRange"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set\"})\r",
     "legendFormat": "Set"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset\"})\r",
     "legendFormat": "MSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset\"})\r",
     "legendFormat": "GetSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append\"})\r",
     "legendFormat": "Append"
    },
    {
     "expr": " max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del\"})\r",
     "legendFormat": "Del"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange\"})\r",
     "legendFormat": "SetRange"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr\"})\r",
     "legendFormat": "Incr"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget\"})",
     "legendFormat": "TsGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd\"})",
     "legendFormat": "TsAdd"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime\"})",
     "legendFormat": "TsRangeByTime"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem\"})",
     "legendFormat": "TsRem"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers\"})",
     "legendFormat": "SMembers"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember\"})",
     "legendFormat": "SIsMember"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard\"})",
     "legendFormat": "SCard"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen\"})",
     "legendFormat": "StrLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd\"})",
     "legendFormat": "SAdd"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem\"})",
     "legendFormat": "SRem"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo\"})\r",
     "legendFormat": "Echo"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth\"})\r",
     "legendFormat": "Auth"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config\"})\r",
     "legendFormat": "Config"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info\"})\r",
     "legendFormat": "Info"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role\"})\r",
     "legendFormat": "Role"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping\"})\r",
     "legendFormat": "Ping"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit\"})\r",
     "legendFormat": "Quit"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb\"})\r",
     "legendFormat": "FlushDB"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command\"})\r",
     "legendFormat": "Command"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget\"})\r",
     "legendFormat": "HGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget\"})\r",
     "legendFormat": "HMGet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall\"})\r",
     "legendFormat": "HGetAll"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys\"})\r",
     "legendFormat": "HKeys"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals\"})\r",
     "legendFormat": "HVals"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen\"})\r",
     "legendFormat": "HLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists\"})\r",
     "legendFormat": "HExists"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen\"})\r",
     "legendFormat": "HStrLen"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset\"})\r",
     "legendFormat": "HSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset\"})\r",
     "legendFormat": "HMSet"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel\"})\r",
     "legendFormat": "HDel"
    },
    {
     "expr": "max(rpc_latency{node_prefix=\"$dbcluster\",quantile=\"p99\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby\"})\r",
     "legendFormat": "HIncrBy"
    }
   ]
  },
  {
   "title": "Total YEDIS Ops / Sec -- Hash",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 437 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget_count\"}[5m]))\r",
     "legendFormat": "HGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget_count\"}[5m]))\r",
     "legendFormat": "HMGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall_count\"}[5m]))\r",
     "legendFormat": "HGetAll"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys_count\"}[5m]))\r",
     "legendFormat": "HKeys"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals_count\"}[5m]))\r",
     "legendFormat": "HVals"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen_count\"}[5m]))\r",
     "legendFormat": "HLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists_count\"}[5m]))\r",
     "legendFormat": "HExists"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen_count\"}[5m]))\r",
     "legendFormat": "HStrLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset_count\"}[5m]))\r",
     "legendFormat": "HSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset_count\"}[5m]))\r",
     "legendFormat": "HMSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel_count\"}[5m]))\r",
     "legendFormat": "HDel"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby_count\"}[5m]))\r",
     "legendFormat": "HIncrBy"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency -- Hash",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 437 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hget_count\"}[5m]))\r",
     "legendFormat": "HGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmget_count\"}[5m]))\r",
     "legendFormat": "HMGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hgetall_count\"}[5m]))\r",
     "legendFormat": "HGetAll"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hkeys_count\"}[5m]))\r",
     "legendFormat": "HKeys"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hvals_count\"}[5m]))\r",
     "legendFormat": "HVals"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hlen_count\"}[5m]))\r",
     "legendFormat": "HLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hexists_count\"}[5m]))\r",
     "legendFormat": "HExists"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hstrlen_count\"}[5m]))\r",
     "legendFormat": "HStrLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hset_count\"}[5m]))\r",
     "legendFormat": "HSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hmset_count\"}[5m]))\r",
     "legendFormat": "HMSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hdel_count\"}[5m]))\r",
     "legendFormat": "HDel"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_hincrby_count\"}[5m]))\r",
     "legendFormat": "HIncrBy"
    }
   ]
  },
  {
   "title": "Total YEDIS Ops / Sec -- TS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 446 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget_count\"}[5m]))",
     "legendFormat": "TsGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd_count\"}[5m]))",
     "legendFormat": "TsAdd"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count\"}[5m]))",
     "legendFormat": "TsRangeByTime"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem_count\"}[5m]))",
     "legendFormat": "TsRem"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency -- TS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 446 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsget_count\"}[5m]))\r",
     "legendFormat": "TsGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsadd_count\"}[5m]))\r",
     "legendFormat": "TsAdd"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrangebytime_count\"}[5m]))\r",
     "legendFormat": "TsRangeByTime"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_tsrem_count\"}[5m]))\r",
     "legendFormat": "TsRem"
    }
   ]
  },
  {
   "title": "Total YEDIS Ops / Sec -- Set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 455 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers_count\"}[5m]))",
     "legendFormat": "SMembers"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember_count\"}[5m]))",
     "legendFormat": "SIsMember"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard_count\"}[5m]))",
     "legendFormat": "SCard"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))",
     "legendFormat": "StrLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd_count\"}[5m]))",
     "legendFormat": "SAdd"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem_count\"}[5m]))",
     "legendFormat": "SRem"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency -- Set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 455 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_smembers_count\"}[5m]))\r",
     "legendFormat": "SMembers"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sismember_count\"}[5m]))\r",
     "legendFormat": "SIsMember"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_scard_count\"}[5m]))\r",
     "legendFormat": "SCard"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))\r",
     "legendFormat": "StrLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_sadd_count\"}[5m]))\r",
     "legendFormat": "SAdd"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_srem_count\"}[5m]))\r",
     "legendFormat": "SRem"
    }
   ]
  },
  {
   "title": "Total YEDIS Ops / Sec -- Sorted Set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 464 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zadd_count\"}[5m]))",
     "legendFormat": "ZAdd"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrem_count\"}[5m]))",
     "legendFormat": "ZRem"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zcard_count\"}[5m]))",
     "legendFormat": "ZCard"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrevrange_count\"}[5m]))",
     "legendFormat": "ZRangeByScore"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrangebyscore_count\"}[5m]))",
     "legendFormat": "ZRevRange"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency -- Sorted Set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 464 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zadd_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zadd_count\"}[5m]))\r",
     "legendFormat": "ZAdd"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrem_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrem_count\"}[5m]))\r",
     "legendFormat": "ZRem"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zcard_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zcard_count\"}[5m]))\r",
     "legendFormat": "ZCard"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrevrange_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrevrange_count\"}[5m]))\r",
     "legendFormat": "ZRevRange"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrangebyscore_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_zrangebyscore_count\"}[5m]))\r",
     "legendFormat": "ZRangeByScore"
    }
   ]
  },
  {
   "title": "Total YEDIS Ops / Sec -- Str",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 473 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get_count\"}[5m]))\r",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget_count\"}[5m]))\r",
     "legendFormat": "MGet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))\r",
     "legendFormat": "StrLen"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists_count\"}[5m]))\r",
     "legendFormat": "Exists"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange_count\"}[5m]))\r",
     "legendFormat": "GetRange"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set_count\"}[5m]))\r",
     "legendFormat": "Set"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset_count\"}[5m]))\r",
     "legendFormat": "MSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset_count\"}[5m]))\r",
     "legendFormat": "GetSet"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append_count\"}[5m]))\r",
     "legendFormat": "Append"
    },
    {
     "expr": " sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del_count\"}[5m]))\r",
     "legendFormat": "Del"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange_count\"}[5m]))\r",
     "legendFormat": "SetRange"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr_count\"}[5m]))\r",
     "legendFormat": "Incr"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency -- Str",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 473 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_get_count\"}[5m]))\r",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mget_count\"}[5m]))\r",
     "legendFormat": "MGet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_strlen_count\"}[5m]))\r",
     "legendFormat": "StrLen"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_exists_count\"}[5m]))\r",
     "legendFormat": "Exists"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getrange_count\"}[5m]))\r",
     "legendFormat": "GetRange"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_set_count\"}[5m]))\r",
     "legendFormat": "Set"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_mset_count\"}[5m]))\r",
     "legendFormat": "MSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_getset_count\"}[5m]))\r",
     "legendFormat": "GetSet"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_append_count\"}[5m]))\r",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_del_count\"}[5m]))\r",
     "legendFormat": "Del"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_setrange_count\"}[5m]))\r",
     "legendFormat": "SetRange"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_incr_count\"}[5m]))\r",
     "legendFormat": "Incr"
    }
   ]
  },
  {
   "title": "Total YEDIS Ops / Sec -- Others",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 482 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo_count\"}[5m]))\r",
     "legendFormat": "Echo"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth_count\"}[5m]))\r",
     "legendFormat": "Auth"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config_count\"}[5m]))\r",
     "legendFormat": "Config"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info_count\"}[5m]))\r",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role_count\"}[5m]))\r",
     "legendFormat": "Role"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping_count\"}[5m]))\r",
     "legendFormat": "Ping"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit_count\"}[5m]))\r",
     "legendFormat": "Quit"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb_count\"}[5m]))\r",
     "legendFormat": "FlushDB"
    },
    {
     "expr": "sum(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command_count\"}[5m]))\r",
     "legendFormat": "Command"
    }
   ]
  },
  {
   "title": "YEDIS Op Latency -- Others",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 482 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_echo_count\"}[5m]))\r",
     "legendFormat": "Echo"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_auth_count\"}[5m]))\r",
     "legendFormat": "Auth"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_config_count\"}[5m]))\r",
     "legendFormat": "Config"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_info_count\"}[5m]))\r",
     "legendFormat": "Info"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_role_count\"}[5m]))\r",
     "legendFormat": "Role"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_ping_count\"}[5m]))\r",
     "legendFormat": "Ping"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_quit_count\"}[5m]))\r",
     "legendFormat": "Quit"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_flushdb_count\"}[5m]))\r",
     "legendFormat": "FlushDB"
    },
    {
     "expr": "avg(rate(rpc_latency_sum{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command_sum\"}[5m])) / avg(rate(rpc_latency_count{node_prefix=\"$dbcluster\",saved_name=\"handler_latency_yb_redisserver_RedisServerService_command_count\"}[5m]))\r",
     "legendFormat": "Command"
    }
   ]
  },
  {
   "title": "RPC queue sizes (YEDIS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 491 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rpcs_in_queue_yb_redisserver_RedisServerService{node_prefix=\"$dbcluster\"})",
     "legendFormat": "YEDIS RPC - Max"
    },
    {
     "expr": "rpcs_in_queue_yb_redisserver_RedisServerService{node_prefix=\"$dbcluster\"}",
     "legendFormat": "YEDIS RPC - {{exported_instance}}"
    }
   ]
  },
  {
   "title": "YBClient Reactor Delays",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 491 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(irate(rpc_incoming_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"redis_export\"}[5m])) / avg(irate(rpc_incoming_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"redis_export\"}[5m]))\r",
     "legendFormat": "Incoming Queue"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_transfer_sum{node_prefix=\"$dbcluster\",export_type=\"redis_export\"}[5m])) / avg(irate(handler_latency_outbound_transfer_count{node_prefix=\"$dbcluster\",export_type=\"redis_export\"}[5m]))\r",
     "legendFormat": "Outbound transfer time"
    },
    {
     "expr": "avg(irate(handler_latency_outbound_call_queue_time_sum{node_prefix=\"$dbcluster\",export_type=\"redis_export\"}[5m])) / avg(irate(handler_latency_outbound_call_queue_time_count{node_prefix=\"$dbcluster\",export_type=\"redis_export\"}[5m]))\r",
     "legendFormat": "Outbound queue time"
    }
   ]
  }
 ]
}